apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: kafkagolang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: producer
          image: your-dockerhub-username/kafka-producer:latest
          env:
            - name: KAFKA_BROKERS
              value: "my-kafka:9092"
            - name: KAFKA_TOPIC
              value: "TEST_TOPIC"
